# databse setup for development 
version: '3.8'
services:
  postgres:
    build: .
    container_name: planzo-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planzo-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

volumes:
  postgres-data: